name: ⚙️ Build library

on:
  workflow_call:

permissions:
  contents: read

env:
  node_version: 24.x

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Use Node.js ${{ env.node_version }}

        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.node_version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Setup Aikido safe-chain
        run: |
          npm i -g @aikidosec/safe-chain
          safe-chain setup-ci

      - name: Downgrade npm for v24 and v25
        # https://github.com/npm/cli/issues/8669
        if: ${{ env.node_version == '24.x' || env.node_version == '25.x' }}
        run: npm i -g npm@11.6.0

      - name: Set up Rust
        run: |
          rustup toolchain install stable
          rustup default stable

      - name: Install wasm-pack
        run: bash ./.github/workflows/utils/install-wasm-pack.sh

      - name: Install dependencies (library only)
        run: npm run install-lib-only

      - name: Build complete library
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: firewall-node-library-${{ github.sha }}
          if-no-files-found: error
          retention-days: 7
          path: |
            build/
            library/internals/
            library/node_internals/
            library/agent/hooks/instrumentation/wasm/
