name: Main Workflow

on:
  push: {}

permissions:
  contents: read

jobs:
  build:
    name: âš™ï¸ Build library
    uses: ./.github/workflows/build.yml
  lint-code:
    name: ğŸ§¹ Lint code
    uses: ./.github/workflows/lint-code.yml
    needs: build
  unit-tests:
    name: ğŸ§ª Unit tests
    uses: ./.github/workflows/unit-test.yml
    needs: build
    permissions:
      contents: read
      id-token: write
  end-to-end-tests:
    name: ğŸ•µï¸ End to end tests
    uses: ./.github/workflows/end-to-end-tests.yml
    needs: build
  benchmark:
    name: ğŸ“Š Benchmark
    uses: ./.github/workflows/benchmark.yml
    needs: build
  qa-tests:
    name: ğŸ§ª QA Tests
    uses: ./.github/workflows/qa-tests.yml
    needs: build
  alpine-test:
    name: ğŸ”ï¸ Alpine test
    uses: ./.github/workflows/alpine-test.yml
    needs: build
